{{- if eq (.Values.controllerManager.enabled | toString) "true" }}
{{- $fullname := include "spire.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-controller-manager" $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.controllerManager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicaCount }}
  selector:
    matchLabels:
      {{- include "spire.controllerManager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controllerManager.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spire.controllerManager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ printf "%s-%s" $fullname .name }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "spire.serviceAccountName" . }}-agent
      securityContext:
        {{- toYaml .Values.controllerManager.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-controller-manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "spire.image" (dict "appVersion" $.Chart.AppVersion "image" .Values.controllerManager.image) }}
          imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy }}
          args:
          - "--config=spire-controller-manager-config.yaml"
          ports:
            - containerPort: 9443
          volumeMounts:
            - name: spire-server-socket
              mountPath: /run/spire/server-sockets
              readOnly: true
            - name: spire-controller-manager-config
              mountPath: /spire-controller-manager-config.yaml
              subPath: spire-controller-manager-config.yaml
          resources:
            {{- toYaml .Values.controllerManager.resources | nindent 12 }}
      volumes:
        - name: spire-server-socket
          hostPath:
            path: /run/spire/server-sockets
            type: DirectoryOrCreate
        - name: spire-controller-manager-config
          configMap:
            name: {{ include "spire.fullname" . }}-controller-manager-config
      {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
