{{- if eq (.Values.controllerManager.enabled | toString) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "spire.server.selectorLabels" . | nindent 4 }}
{{- end }}

